### ISSUE TITLE
Milestone tracker: v.1.0.0

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#19]
- [x] Reorganise original Godot-D code. 
 #9
 #10

- [ ] Parity (make it closer to GDScript and C#) 
 #24
 #31
 #35

- [ ] Get rid of template-based type system (`GodotScript!Node`, `gs!"string"`). 
 #8
 #11
 #12

- [ ] Port pregenerator for gd4 (auto-generate `GodotNativeLibrary!` mixins). 
 #13

- [ ] Fix extension issues. 
 #3
 #4
 #5

- [ ] Fix generator issues. 
 #6
 #7

- [ ] Fix any memory leaks. 
 #16 

- [ ] User convinience. 
 #18
 #27
 #23
 #26 

- [ ] Documentation.
 #30 
 #33 
 #34

**Comment by al1-ce** [comment]
Closing in favour of [Milestone 1](https://github.com/godot-dlang/godot-dlang/milestone/1)
